### ISSUE TITLE
Date Question results not Serializing correctly

### ISSUE THREAD

**Issue by apbendi** [cloudmine/CMHealthSDK-iOS#66]
Result to this question generates an error in the base SDK:

```Swift
ORKQuestionStep(identifier: "SwiftyHealthBirthQuestion", title: "When were you born?", answer: ORKAnswerFormat.dateAnswerFormat())
```

**Comment by kothapas** [comment]
Is there a workaround on this? I keep getting the error that you can only story simple values, dictionaries, and arrays in CMObject instance variables

**Comment by apbendi** [comment]
No workaround yet, but this is high on the list to get resolved. We'd love to here any information on your usage of the SDK and any feedback or suggestions you'd have. Feel free to reach out!

**Comment by kothapas** [comment]
Is there a way we can change the NSDate return object into something we can actually use? Like a UTC time.

**Comment by apbendi** [comment]
Hey @kothapas, I've just opened a PR that resolves this issue: https://github.com/cloudmine/CMHealthSDK-iOS/pull/73

You could try this out right now by pointing your Podfile at that commit. Once merged, we'll likely do another pre-Beta release to CocoaPods. Let us know how it goes!

**Comment by kothapas** [comment]
would I do that by just doing:

pod 'CMHealth', :commit => 'b593595f'

**Comment by kothapas** [comment]
Hey Ben,

As soon as i update to this commit, I get this error:

**Comment by apbendi** [comment]
hey @kothapas, this is on my fork of the repo, so you'll have to call that out specifically in the CocoaPod. This should work:

`pod 'CMHealth', :git => 'https://github.com/apbendi/CMHealthSDK-iOS.git', :commit => 'b593595f89c75f6442c76824e86a26eaa2050846'`

Let me know how it goes!
