### ISSUE TITLE
saveStudyWithDescriptor

### ISSUE THREAD

**Issue by kothapas** [cloudmine/CMHealthSDK-iOS#71]
This is always returning a created status even though it has the same descriptor, shouldn't it be updated if its with the same descriptor name

**Comment by apbendi** [comment]
hey @kothapas, can you elaborate on your use case? Are you saving an incomplete result in the hopes of completing that task later and then updating the result?

**Comment by kothapas** [comment]
The use case is that we want to be able to give users a 4 hr timelimit on changing their answers to some of the survey questions, whether it was a mistake or just because they forgot to add something?

One of our questions is what other medication did you take?

If they wanted to later add onto this because they forgot.

**Comment by apbendi** [comment]
Got it, make sense! So do users retake the whole survey and put in new answers? Or do pull down the previously completed survey and use that to populate the survey with existing answers filled out? Or is it something more specific?

**Comment by kothapas** [comment]
They would retake the whole survey and it would make the according changes to the existing cloudmine data

**Comment by apbendi** [comment]
hey @kothapas, I just published a PR that should address the functionality you were looking for. Namely, as long as the `taskRunUUID` of the `ORKTask` you present to your users is the same as one of a previously saved survey, it will update the existing record with the new one you create. Exactly how you go about this will depend on your app. It could mean fetching the record and updating, or it could mean creating a brand new `ORKTask` with the same `taskRunUUID` you persisted locally (such as `NSUserDefaults`)

You can check out the PR here: https://github.com/cloudmine/CMHealthSDK-iOS/pull/78

Some things may change before it gets merged. LMK if you have any questions, feedback, or issues!
